# Generated by Django 3.2.18 on 2023-05-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviecomment_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
